#! /bin/bash

set -e

help() {
  echo "Usage: $0 --[create|list|remove|switch] name [--wallet-key mykey] [--leder-role ENDORSER]"
}

# Host and Port for the VON-Network
INDY_WEB_SERVER_HOST=${INDY_WEB_SERVER_PORT:-localhost}
INDY_WEB_SERVER_PORT=${INDY_WEB_SERVER_PORT:-9000}

# Host and Port for ACA-Py
ACAPY_HOSTNAME=${ACAPY_HOSTNAME:-localhost}
ACAPY_ADMIN_PORT=${ACAPY_ADMIN_PORT:-8031}
ACAPY_ADMIN_KEY=${ACAPY_ADMIN_KEY:-adminkey}

ACAPY_USER_PORT=${ACAPY_USER_PORT:-8030}

configDir="${HOME}/.config/acapy/wallet"
mkdir -p ${configDir}

createWallet() {
  walletAlias="$1"
  walletKey="$2"
  ledgerRole="$3"

  if [[ -z ${walletAlias} ]]; then
    help; exit 1
  fi
  if [[ -z ${walletKey} ]]; then
    walletKey="${walletAlias}Key"
  fi

  echo "Create Wallet for ${walletAlias} ..."
  jsonData="{\"wallet_name\":\"${walletAlias}\",\"wallet_key\":\"${walletKey}\",\"wallet_dispatch_type\":\"default\",\"wallet_type\":\"indy\"}"
  echo ${jsonData} | jq .

  jsonResponse=$(curl --silent --request POST "http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}/multitenancy/wallet" \
  	--header "X-API-KEY: ${ACAPY_ADMIN_KEY}" \
  	--data-raw "${jsonData}")
  echo ${jsonResponse} | jq .

  walletId=$(echo ${jsonResponse} | jq -r .wallet_id)
  accessToken=$(echo ${jsonResponse} | jq -r .token)

  echo "Create DID ..."
  jsonResponse=$(curl --silent --request POST "http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}/wallet/did/create" \
  	--header "Authorization: Bearer ${accessToken}" \
  	--header "X-API-KEY: ${ACAPY_ADMIN_KEY}" \
  	--data-raw "{}")
  echo ${jsonResponse} | jq .

  publicDid=$(echo ${jsonResponse} | jq -r .result.did)
  publicVkey=$(echo ${jsonResponse} | jq -r .result.verkey)

  if [[ ! -z ${ledgerRole} ]]; then

    echo "Register DID with the Ledger ..."
    jsonData="{\"alias\":\"${walletAlias}\",\"did\":\"${publicDid}\",\"verkey\":\"${publicVkey}\",\"role\":\"${ledgerRole}\"}"
    echo ${jsonData} | jq .

    jsonResponse=$(curl --silent --request POST "http://${INDY_WEB_SERVER_HOST}:${INDY_WEB_SERVER_PORT}/register" \
    	--data-raw "${jsonData}")
    echo ${jsonResponse} | jq .

    echo "Set the public DID for the wallet"
    jsonResponse=$(curl --silent --request POST "http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}/wallet/did/public?did=${publicDid}" \
    	--header "Authorization: Bearer ${accessToken}" \
    	--header "X-API-KEY: ${ACAPY_ADMIN_KEY}")
    echo ${jsonResponse} | jq .
  fi

  configFile="${configDir}/${walletAlias}.json"

  echo "Wallet Config: ${configFile}"
  jsonData="{\"wallet_name\":\"${walletAlias}\",\"wallet_key\":\"${walletKey}\",\"ledger_role\":\"${ledgerRole}\""
  jsonData="${jsonData},\"wallet_id\":\"${walletId}\",\"did\":\"${publicDid}\",\"verkey\":\"${publicVkey}\",\"auth_token\":\"${accessToken}\"}"
  echo "${jsonData}" > ${configFile}
  cat ${configFile} | jq .

  echo "Create CLI environment for ${walletAlias} ..."
  siera configuration add --environment="${walletAlias}" --agent="aca-py" --agent-url="http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}" --api-key="${ACAPY_ADMIN_KEY}" --token="${accessToken}"
  siera configuration view
}

listWallets() {

  jsonResponse=$(curl --silent --request GET "http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}/multitenancy/wallets" \
    --header "X-API-KEY: ${ACAPY_ADMIN_KEY}")
  echo ${jsonResponse} | jq .
}

removeWallet() {
  walletAlias="$1"

  if [[ -z ${walletAlias} ]]; then
    help; exit 1
  fi

  configFile="${configDir}/${walletAlias}.json"

  if [[ -f ${configFile} ]]; then
    walletId=$(cat ${configFile} | jq -r .wallet_id)

    echo "Remove wallet for ${walletAlias}"
    jsonResponse=$(curl --silent --request POST "http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}/multitenancy/wallet/${walletId}/remove" \
      --header "X-API-KEY: ${ACAPY_ADMIN_KEY}")

    rm ${configFile}

    # [#165] Add support for dropping environments from the config
    # https://github.com/animo/aries-cli/issues/165
  fi
}

switchWallet() {
  walletAlias="$1"

  if [[ -z ${walletAlias} ]]; then
    help; exit 1
  fi

  configFile="${configDir}/${walletAlias}.json"
  accessToken=$(cat ${configFile} | jq -r .auth_token)

  echo "Switching CLI environment to ${walletAlias}"
  siera configuration add --environment="default" --agent-url="http://${ACAPY_HOSTNAME}:${ACAPY_ADMIN_PORT}" --api-key="${ACAPY_ADMIN_KEY}" --token="${accessToken}"
}

options=($@)
for i in "${!options[@]}"
do
  j=$((i + 1))
  key=${options[i]}
  val=${options[j]}

  # echo "$i/$j: ${key} ${val}"

  case ${key} in
    --create | --remove | --switch) walletAlias=${val};;
    --wallet-key) walletKey=${val};;
    --ledger-role) ledgerRole=${val};;
  esac
done

if [[ $1 == "--create" ]]; then

  createWallet "${walletAlias}" "${walletKey}" "${ledgerRole}"

elif [[ $1 == "--list" ]]; then

  listWallets

elif [[ $1 == "--remove" ]]; then

  removeWallet ${walletAlias}

elif [[ $1 == "--switch" ]]; then

  switchWallet ${walletAlias}

else
  help
fi
