{{- with .Values.deployments.issuer_api }}
---

# Issuer API ConfigMap
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: issuer-api-config
data:
  {{- $files := $.Files.Glob "config/issuer-api/config/*" }}
  {{- range $path, $file := $files }}
  {{ base $path }}: |
  {{ toString $file | nindent 4 }}
  {{- end }}
---

# Issuer API Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: issuer-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: issuer-api
    spec:
      containers:
        - name: issuer-api
          image: nessusio/issuer-api:{{ .version }}
          env:
            - name: ISSUER_API_PORT
              value: '7002'
          ports:
            - containerPort: 7002
          volumeMounts:
            - name: config
              mountPath: /waltid-issuer-api/config
      volumes:
        - name: config
          configMap:
            name: issuer-api-config

---

# Issuer API Service
#
apiVersion: v1
kind: Service
metadata:
  name: issuer-api
spec:
  type: NodePort
  ports:
    - port: 7002
      nodePort: {{ .nodePort }}
  selector:
    app.kubernetes.io/name: issuer-api
---

{{- end }}
