{{- with .Values.deployments.opa_server }}
---

# OPA Server Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opa-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opa-server
    spec:
      containers:
        - name: opa-server
          image: openpolicyagent/opa:{{ .version }}
          command: [ "opa", "run", "--server", "--addr", ":8181" ]
          ports:
            - containerPort: 8181
---

{{- if eq $.Values.environment "local" }}
---

# OPA Server Service
#
apiVersion: v1
kind: Service
metadata:
  name: opa-server
spec:
  type: NodePort
  ports:
    - port: 8181
      nodePort: {{ .nodePort }}
  selector:
    app.kubernetes.io/name: opa-server
---

{{- else }}
---

# OPA Server Service
#
apiVersion: v1
kind: Service
metadata:
  name: opa-server
spec:
  type: ClusterIP
  ports:
    - port: 8181
  selector:
    app.kubernetes.io/name: opa-server
---

# OPA Server IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opa-server
  labels:
    app.kubernetes.io/name: opa-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.opaServiceHost }}")
      kind: Rule
      services:
        - name: opa-server
          port: 8181
  tls:
    secretName: origin-tls
---

{{- end }}
{{- end }}
