{{- with .Values.deployments.vc_repo }}
---

# VC Repo Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vc-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vc-repo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vc-repo
    spec:
      containers:
        - name: vc-repo
          image: waltid/vc-repository:{{ .version }}
          env:
            - name: PORT
              value: "7103"
          ports:
            - containerPort: 7103
---

# VC Repo Service
#
apiVersion: v1
kind: Service
metadata:
  name: vc-repo
spec:
  type: ClusterIP
  ports:
    - port: 7103
  selector:
    app.kubernetes.io/name: vc-repo
---

# VC Repo IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vc-repo
  labels:
    app.kubernetes.io/name: vc-repo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vc-repo.nessus-tech.io`)
      kind: Rule
      services:
        - name: vc-repo
          port: 7103
  tls:
    secretName: origin-tls
---

{{- end }}
