{{- with .Values.deployments.verifier_api }}
---

# Verifier API ConfigMap
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: verifier-config
data:
  {{- $files := $.Files.Glob "config/verifier-api/*" }}
  {{- range $path, $file := $files }}
  {{ base $path }}: |
  {{ toString $file | nindent 4 }}
  {{- end }}
---

# Verifier API Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verifier-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: verifier-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: verifier-api
    spec:
      containers:
        - name: verifier-api
          image: {{ $.Values.imagePrefix }}waltid/verifier-api:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          env:
            - name: VERIFIER_API_PORT
              value: '7003'
          ports:
            - containerPort: 7003
          volumeMounts:
            - name: config
              mountPath: /waltid-verifier-api/config
      volumes:
        - name: config
          configMap:
            name: verifier-config
---

{{- if eq $.Values.environment "local" }}
---

# Verifier API Service
#
apiVersion: v1
kind: Service
metadata:
  name: verifier-api
spec:
  type: NodePort
  ports:
    - port: 7003
      nodePort: {{ .nodePort }}
  selector:
    app.kubernetes.io/name: verifier-api
---

{{- else }}
---

# Verifier API Service
#
apiVersion: v1
kind: Service
metadata:
  name: verifier-api
spec:
  type: ClusterIP
  ports:
    - port: 7003
  selector:
    app.kubernetes.io/name: verifier-api
---

# Wallet API IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: verifier-api
  labels:
    app.kubernetes.io/name: verifier-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.verifierApiHost }}")
      kind: Rule
      services:
        - name: verifier-api
          port: 7003
  tls:
    secretName: origin-tls
---

{{- end }}

{{- end }}
