{{- with .Values.deployments.wallet_demo }}
---

# Wallet Demo Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-demo
    spec:
      containers:
        - name: wallet-demo
          image: {{ $.Values.registry }}/waltid/waltid-demo-wallet:{{ .version }}
          imagePullPolicy: Always
          env:
            - name: NUXT_PUBLIC_ISSUER_CALLBACK_URL
              value: "https://wallet.nessus-tech.io"
            - name: PORT
              value: "7101"
          ports:
            - containerPort: 7101
---

# Wallet Demo Service
#
apiVersion: v1
kind: Service
metadata:
  name: wallet-demo
spec:
  type: ClusterIP
  ports:
    - port: 7101
  selector:
    app.kubernetes.io/name: wallet-demo
---

# Wallet Demo IngressRoute
#
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallet-demo
  labels:
    app.kubernetes.io/name: wallet-demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wallet.nessus-tech.io`) && PathPrefix(`/wallet-api`)
      kind: Rule
      services:
        - name: wallet-api
          port: 7001
    - match: Host(`wallet.nessus-tech.io`)
      kind: Rule
      services:
        - name: wallet-demo
          port: 7101
  tls:
    secretName: origin-tls
---

{{- end }}
