{{- with .Values.deployments.wallet_dev }}
---

# Wallet Dev Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wallet-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallet-dev
    spec:
      containers:
        - name: wallet-dev
          image: {{ $.Values.registry }}/waltid/waltid-dev-wallet:{{ .version }}
          imagePullPolicy: Always
          env:
            - name: NUXT_PUBLIC_ISSUER_CALLBACK_URL
              value: "https://wallet-dev.nessus-tech.io"
            - name: NUXT_PUBLIC_DEMO_WALLET_URL
              value: "https://wallet.nessus-tech.io"
            - name: PORT
              value: "7104"
          ports:
            - containerPort: 7104
---

# Wallet Dev Service
#
apiVersion: v1
kind: Service
metadata:
  name: wallet-dev
spec:
  type: ClusterIP
  ports:
    - port: 7104
  selector:
    app.kubernetes.io/name: wallet-dev
---

# Wallet Dev IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wallet-dev
  labels:
    app.kubernetes.io/name: wallet-dev
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wallet-dev.nessus-tech.io`) && PathPrefix(`/wallet-api`)
      kind: Rule
      services:
        - name: wallet-api
          port: 7001
    - match: Host(`wallet-dev.nessus-tech.io`)
      kind: Rule
      services:
        - name: wallet-dev
          port: 7104
  tls:
    secretName: origin-tls
---

{{- end }}
