{{- with .Values.deployments.web_portal }}
---

# Web Portal Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-portal
    spec:
      containers:
        - name: web-portal
          image: {{ $.Values.imagePrefix }}waltid/portal:{{ .version }}
          imagePullPolicy: {{ .pullPolicy }}
          env:
            - name: NEXT_PUBLIC_VC_REPO
              value: "{{ $.Values.urlSchema }}://{{ $.Values.repoServiceHost }}"
            - name: NEXT_PUBLIC_ISSUER
              value: "{{ $.Values.urlSchema }}://{{ $.Values.issuerApiHost }}"
            - name: NEXT_PUBLIC_VERIFIER
              value: "{{ $.Values.urlSchema }}://{{ $.Values.verifierApiHost }}"
            - name: NEXT_PUBLIC_WALLET
              value: "{{ $.Values.urlSchema }}://{{ $.Values.demoWalletHost }}"
            - name: PORT
              value: "7102"
          ports:
            - containerPort: 7102
---

{{- if eq $.Values.environment "local" }}
---
# Web Portal Service
#
apiVersion: v1
kind: Service
metadata:
  name: web-portal
spec:
  type: NodePort
  ports:
    - port: 7102
      nodePort: {{ .nodePort }}
  selector:
    app.kubernetes.io/name: web-portal
---

{{- else }}
---
# Web Portal Service
#
apiVersion: v1
kind: Service
metadata:
  name: web-portal
spec:
  type: ClusterIP
  ports:
    - port: 7102
  selector:
    app.kubernetes.io/name: web-portal
---

# Web Portal IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-portal
  labels:
    app.kubernetes.io/name: web-portal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("{{ $.Values.webPortalHost }}")
      kind: Rule
      services:
        - name: web-portal
          port: 7102
  tls:
    secretName: origin-tls
---
{{- end }}

{{- end }}
