{{- with .Values.deployments.web_portal }}
---

# Web Portal Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-portal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-portal
    spec:
      containers:
        - name: web-portal
          image: {{ $.Values.registry }}/waltid/portal:{{ .version }}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "7102"
          ports:
            - containerPort: 7102
---

# Web Portal Service
#
apiVersion: v1
kind: Service
metadata:
  name: web-portal
spec:
  type: ClusterIP
  ports:
    - port: 7102
  selector:
    app.kubernetes.io/name: web-portal
---

# Web Portal IngressRoute
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-portal
  labels:
    app.kubernetes.io/name: web-portal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`web-portal.nessus-tech.io`)
      kind: Rule
      services:
        - name: web-portal
          port: 7102
  tls:
    secretName: origin-tls
---

{{- end }}
