#
# helm upgrade --kube-context=ebsi --install ebsi-portal ./helm -f ./helm/values-ebsi-portal.yaml
#

environment: k3s

urlSchema: "https"
imagePrefix: "registry.vps6c.eu.ebsi:30443/"


deployments:

  ebsi_portal:
    version: latest
    pullPolicy: Always
