#
# helm upgrade --install identity ./helm -f ./helm/values-services-local.yaml
#

environment: local

urlSchema: "http"

demoWalletHost: "kubernetes.docker.internal:32101"
devWalletHost: "kubernetes.docker.internal:32102"
webPortalHost: "kubernetes.docker.internal:32103"

walletApiHost: "kubernetes.docker.internal:32001"
issuerApiHost: "kubernetes.docker.internal:32002"
verifierApiHost: "kubernetes.docker.internal:32003"

opaServiceHost: "kubernetes.docker.internal:32181"
repoServiceHost: "kubernetes.docker.internal:32104"
vaultServiceHost: "kubernetes.docker.internal:32200"

deployments:

  wallet_api:
    version: 0.13.0-dev
    nodePort: 32001
    pullPolicy: IfNotPresent

  issuer_api:
    version: 0.13.0-dev
    nodePort: 32002
    pullPolicy: IfNotPresent

  verifier_api:
    version: 0.13.0-dev
    nodePort: 32003
    pullPolicy: IfNotPresent

  wallet_demo:
    version: 0.13.0-dev
    nodePort: 32101
    pullPolicy: IfNotPresent

  wallet_dev:
    version: 0.13.0-dev
    nodePort: 32102
    pullPolicy: IfNotPresent

  web_portal:
    version: 0.13.0-dev
    nodePort: 32103
    pullPolicy: IfNotPresent

  vc_repo:
    version: latest
    nodePort: 32104

  vault:
    version: 1.19
    nodePort: 32200

  opa_server:
    version: 1.4.2
    nodePort: 32181



